### ISSUE TITLE
Prepare for Debian Bullseye

### ISSUE THREAD

**Issue by HendrikF** [tribut/ipset-rpcd#3]
The systemd unit references `/usr/bin/python`, but Debian Bullseye only comes with `python2.7`, `3` and `3.9`.

The code itself should be Python 3 compatible since our last refactor, so it's just a matter of changing the unit file.

Also we should include a `requirements.txt` for `jsonrpclib`. Add to `README` too.

**Comment by HendrikF** [comment]
Sudoers also needs a small fix. `ipset` moved from `/sbin/ipset` to `/usr/sbin/ipset`.

**Comment by tribut** [comment]
Looks good – do you want me to prepare a patch or is this just a note for yourself? :)
